create database Computer;
use Computer;
create table info_data(pinCode int,state_name varchar(20),state_capital varchar(30),state_food varchar(40),state_fruit varchar(30),state_tree varchar(40),state_popu bigint,state_gov varchar(30),state_size bigint,state_dance varchar(40));
desc info_data;
alter table info_data add column state_language varchar(30);
alter table info_table add column state_education varchar(30);
alter table info_data add column state_education varchar(30);
alter table info_data add column state_health varchar(30);
alter table info_data add column state_crop varchar(30);
alter table info_data add column state_temp varchar(30);
alter table info_data rename column state_crop to sta_crops;
alter table info_data rename column state_name to name_of_state;
alter table info_data rename column state_capital to capital_city;
alter table info_data rename column state_language to sta_language;
alter table info_data rename column state_food to food_state;
alter table info_data modify column pinCode bigint;
alter table info_data add column economy_ratings varchar(20);
alter table info_data modify column economy_ratings int;
alter table info_data add column emplo_rates varchar(30);
alter table info_data modify column emplo_rates int;
alter table info_data add column stat_health_stati varchar(40);
alter table info_data modify column stat_health_stati int;
alter table info_data add column sta_dist varchar(20);
alter table info_data modify column sta_dist int;
select* from info_data;
alter table info_data rename column pinCode to state_code;
insert into info_data values(29,'Karnataka','Bengaluru','Dosas','Mango','JackFruit',70000000,'Congress',191791,'Yakshagana','Kannada','KSEEB','Good','Rice','24',78,85,89,31); 
alter table info_data drop column economy_ratings;
alter table info_data drop column emplo_rates;
alter table info_data drop column sta_health_stati;
alter table info_data drop column stat_health_stati;
alter table info_data drop column state_health;
alter table info_data drop column state_temp;
alter table info_data drop column state_size;
alter table info_data drop column state_education;

