create database information;
use information;
create table info_hos(hospital_id int,hos_name varchar(30),hos_add varchar(50),doc_id int,doc_name varchar(20),doc_address varchar(30),no_of_doc int,no_of_staff int,ratings int,hygine varchar(30));
desc info_hos;
insert into info_hos values(2,'M G Hospital','Jakkur',6,'Ranya','Guttalli',60,55,5,'good');
insert into info_hos values(7,'HK Hospital','Vidhya nagar',5,'Reeta','Jayanagar',40,20,4,'bad');
insert into info_hos values(5,'Jaydeva','BTM',8,'Bhuvan','Vidhya Nagar',70,60,5,'Great');
insert into info_hos values(1,'Nimhans','Batrayanapura',7,'Chethana','Davanagere',50,30,5,'good');
insert into info_hos values(3,'SSMS','Davanagere',8,'Meghana','Bengaluru',45,30,5,'bad');
insert into info_hos values(4,'SSISM','Mysore',6,'Chandana','Dhrawad',70,55,5,'good');
insert into info_hos values(2,'JMC','Hubli',9,'Veena','Guttalli',40,55,5,'good');
insert into info_hos values(2,'HIMS','Jakkur',6,'Malleshwaram','Guttalli',60,55,5,'good');
insert into info_hos values(8,'SIMS','Jakkur',5,'Ranya','Guttalli',60,55,5,'good');
insert into info_hos values(11,'RMIS','Jakkur',4,'Rita','Mysore',50,30,5,'good');
insert into info_hos values(89,'GK Hospital','Davanagere',3,'Ranya','Bengaluru',10,20,4,'bad');
insert into info_hos values(77,'HTM Hospital','Mysore',4,'Yana','Hubli',20,40,2,'bad');
insert into info_hos values(56,'IMS','Jakkur',6,'Tanisha','bellary',60,30,5,'good');
insert into info_hos values(99,'RT Hospital','DVG',6,'Pushpa','Hubli',70,30,5,'good');
insert into info_hos values(44,'YBR Hospital','Mysore',3,'Latha','Guttalli',60,55,5,'good');
insert into info_hos values(33,'RTN Hospital','Mangalore',2,'Yasini','Hassan',40,20,4,'good');
insert into info_hos values(21,'RHN Hospital','Bidar',8,'Reena','Guttalli',60,55,5,'good');
insert into info_hos values(90,'MGM Hospiatal','Yadgiri',2,'Manya','BTM',20,45,4,'bad');
insert into info_hos values(67,'Deepam Hospital','Dandeli',9,'kavya','Bellary',30,55,4,'good');
insert into info_hos values(78,'KGM Hospital','Mandya',5,'Sanjali','Hubli',70,55,4,'good');
Select * from info_hos;