CREATE DATABASE jun_17;
CREATE DATABASE xworkz;
USE xworkz;
CREATE TABLE employee(id int,emp_name varchar(20),emp_sal bigint,emp_loc varchar(10));
CREATE DATABASE Workers;
USE Workers;
CREATE TABLE details(id int,worker_names varchar(50),workers_salary bigint(10),workers_loc varchar(10));
DESC details;
USE workers;
DESC details;
SHOW DATABASES;