create database Bengaluru;
use Bengaluru;
create table employee_details(id int,e_name varchar(20),e_address varchar(30),e_no bigint,e_salary bigint);
Select* from employee_details;
desc employee_details;
alter table employee_details add column e_bonus bigint;
alter table employee_details add column e_age int;
alter table employee_details add column e_dob int;
alter table employee_details add column e_work varchar(30);
alter table employee_details add column e_eligibility varchar(10);
alter table employee_details drop column e_age;
alter table employee_details drop column e_work;
alter table employee_details rename column e_no to e_number;
alter table employee_details rename column e_name to employee_name;
alter table employee_details rename column e_salary to employee_salary;
alter table employee_details rename column e_address to employee_address;
alter table employee_details rename column id to employee_id;
alter table employee_details modify column e_eligibility int;
alter table employee_details modify column e_number int;
alter table employee_details modify column employee_id bigint;
alter table employee_details modify column e_bonus int;
alter table employee_details modify column employee_name bigint;
