create database Mysore;
use Mysore;
create table airport_details(flight_no int,fight_name varchar(10),a_address varchar(20));
alter table airport_details add column flight_landing_area varchar(30);
alter table airport_details add column a_food_services varchar(20);
alter table airport_details add column a_security varchar(20);
alter table airport_details add column a_wi_fi int;
alter table airport_details add column a_fire_stations varchar(10);
desc airport_details;
alter table airport_details drop column a_wi_fi;
alter table airport_details drop column a_fire_stations;
alter table airport_details rename column a_address to airport_address;
alter table airport_details rename column a_food_services to airport_food_services;
alter table airport_details rename column a_security to airport_security;
alter table airport_details rename column fight_name to flight_information;
alter table airport_details rename column flight_landing_area to landing_time;
alter table airport_details modify column airport_address bigint;
alter table airport_details modify column airport_security int;
alter table airport_details modify column airport_food_services bigint;
alter table airport_details modify column flight_no bigint;
alter table airport_details modify column landing_time int;